# Generated by Django 4.1 on 2022-10-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=250, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=1500, verbose_name='Descripcion')),
                ('direccion', models.CharField(blank=True, max_length=45, verbose_name='Direccion')),
                ('horario', models.CharField(blank=True, max_length=50, verbose_name='Horario')),
                ('diasH', models.CharField(blank=True, max_length=50, verbose_name='Dias')),
                ('foto', models.FileField(blank=True, upload_to='', verbose_name='Foto')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualizacion')),
            ],
        ),
    ]
