# Generated by Django 4.1 on 2022-10-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='foto',
            field=models.FileField(blank=True, upload_to='images/', verbose_name='Foto'),
        ),
    ]
