# Generated by Django 4.1 on 2022-10-11 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_oficina_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='encargados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=60, verbose_name='Nombre')),
                ('dpi', models.CharField(blank=True, max_length=15, verbose_name='DPI')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('profesion', models.CharField(blank=True, max_length=35, verbose_name='Profesion')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualizacion')),
            ],
        ),
        migrations.CreateModel(
            name='proyectoslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=250, verbose_name='Nombre')),
                ('lugar', models.CharField(blank=True, max_length=200, verbose_name='Lugar')),
                ('fechaApertura', models.DateField(blank=True, verbose_name='FechaApertura')),
                ('fechaFinal', models.DateField(blank=True, verbose_name='FechaFinal')),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=3, max_digits=20, verbose_name='Presupuesto')),
                ('tiempo', models.CharField(blank=True, max_length=30, verbose_name='Tiempo')),
                ('descripcio', models.TextField(blank=True, verbose_name='Descripcio')),
                ('foto', models.FileField(blank=True, upload_to='images/', verbose_name='Foto')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualizacion')),
                ('encargado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.encargados')),
            ],
        ),
    ]
