# Generated by Django 4.1 on 2022-10-14 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_avances'),
    ]

    operations = [
        migrations.DeleteModel(
            name='avances',
        ),
    ]
